version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install "parallel" package to speed up the build
          command: sudo apt-get update && sudo apt-get install -y parallel
      - run:
          name: Run build.sh to build all the Docker images
          command: bash build.sh

workflows:
  version: 2
  build:
    jobs:
      - build